
version: '2'
services:

    app_nginx:
        image: "nginx:latest"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/tmp/:/tmp/"
            - "./config/nginx/:/etc/nginx/"
            - "./log/nginx/:/var/log/nginx/"
            - "./www/:/var/www/html/"
        links:
            - "app_php"
        command: "nginx -g 'daemon off;'"
        restart: "always"

    app_php:
        build: "./app_php"
        volumes:
            - "/tmp/:/tmp/"
            - "./config/php-fpm/:/etc/php-fpm.d/"
            - "./log/php-fpm/:/var/log/php-fpm/"
            - "./www/:/var/www/html/"
        links:
            - "app_mysql"
            - "app_postgres"
        command: "php-fpm --nodaemonize"
        restart: "always"

    app_mysql:
        image: "mysql:latest"
        volumes:
            - "/tmp/:/tmp/"
            - "./config/mysql/:/etc/mysql/"
            - "./log/mysql/:/var/log/mysql/"
            - "./db/mysql/:/var/lib/mysql/"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        restart: "always"

    app_postgres:
        image: "postgres:latest"
        volumes:
            - "/tmp/:/tmp/"
            - "./config/postgres/:/etc/postgres/"
            - "./log/postgres/:/var/log/postgresql/"
            - "./db/postgres/data/:/var/lib/postgresql/data/"
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "root"
        restart: "always"

